name: projectflutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0  # ou a última versão disponível
  supabase_flutter: ^2.8.4
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7 # ou a versão mais recente
  image_picker: ^0.8.7+3
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/