name: projectflutter
description: "A new Flutter project."

# A linha abaixo impede que o pacote seja publicado acidentalmente no pub.dev
# usando `flutter pub publish`. Isso é preferido para pacotes privados.
publish_to: 'none' # Remova esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4  # Atualização para a versão mais recente (verifique se há uma versão mais recente em pub.dev)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

